name: 'update'
on: 
  push:
  schedule:
    - cron: '0 3 */2 * *'
jobs:
  run_bash:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
        
      - name: 'run the script'
        run: bash ./cron/ip.sh
        
      - name: 'Commit'
        run: |
          git config --global user.email 114452622+w2599@users.noreply.github.com
          git config --global user.name w2599
          git add .
          git commit -m"update"
        
      - name: 'Push changes'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
